#!/bin/sh
set -e

if [ "$BASE_PATH" ]; then
    d="/var/www/html/`dirname $BASE_PATH`"
    n="`basename $BASE_PATH`"
    [ ! -e "$d" ] && mkdir -p "$d"
    ln -s /usr/share/pdns "$d/$n"
else
    rm -rf /var/www/html
    ln -s /usr/share/pdns /var/www/html
fi

cat <<EOF > /usr/share/pdns/inc/config.inc.php
<?php

\$db_host        = '${DB_HOST:?}';
\$db_user        = '${DB_USER:?}';
\$db_pass        = '${DB_PASS:?}';
\$db_name        = '${DB_NAME:?}';
\$db_type        = 'pgsql';
\$db_layer       = 'PDO';

\$session_key        = '${SESSION_KEY:?}';

\$iface_lang     = 'en_EN';

\$dns_hostmaster     = '${DNS_HOSTMASTER:?}';
\$dns_ns1        = '${DNS_NS1:?}';
\$dns_ns2        = '${DNS_NS2:?}';
EOF

exec docker-php-entrypoint "$@"
